apiVersion: v2
name: temporal
description: Helm chart for Temporal service deployment
type: application
version: 0.1.0
appVersion: "1.21.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled